# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgxman < Formula
  desc "PostgreSQL Extensions Manager"
  homepage "https://github.com/pgxman/pgxman"
  version "0.1.20"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgxman/release/releases/download/v0.1.20/pgxman_darwin_amd64.tar.gz"
      sha256 "511ee348fec3639388ba599cb780342ac20ab1c28857f75d58d47bab7d00d07a"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgxman/release/releases/download/v0.1.20/pgxman_darwin_arm64.tar.gz"
      sha256 "186cdda861c266c4be03e7633c15b1c2048e25f5cef822520f9ab65d74fe3dc4"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pgxman/release/releases/download/v0.1.20/pgxman_linux_amd64.tar.gz"
      sha256 "09506fa04debf4175db22343a4175cca52634780f53805348e04cf8cfdbcfcee"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pgxman/release/releases/download/v0.1.20/pgxman_linux_armv6.tar.gz"
      sha256 "b14168be7b182572785ec672431398e3cc4ef518d6095d1358d523fc6dd3be97"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgxman/release/releases/download/v0.1.20/pgxman_linux_arm64.tar.gz"
      sha256 "60569ef698c574c66f676a5f5da1abd8beeeedb07adc0b9b15fbd62848270aaa"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
  end

  head "https://github.com/pgxman/pgxman.git"

  test do
    assert_match(/pgxman version/, shell_output("#{bin}/pgxman --version"))
  end
end
