# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgxman < Formula
  desc "PostgreSQL Extensions Manager"
  homepage "https://github.com/pgxman/pgxman"
  version "0.1.19"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgxman/release/releases/download/v0.1.19/pgxman_darwin_amd64.tar.gz"
      sha256 "13b4538506634103c854208b6ede33dd81f51dd95ad5b2ecaad4aed34c6fa397"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgxman/release/releases/download/v0.1.19/pgxman_darwin_arm64.tar.gz"
      sha256 "564544c2b6487fc92e3fe4286c2df2f630957b8af918ad21847b0969bd895f03"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pgxman/release/releases/download/v0.1.19/pgxman_linux_amd64.tar.gz"
      sha256 "633bac5e488271ebe8b6ac64c79badf61703da17fb45d33407067888cceca785"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pgxman/release/releases/download/v0.1.19/pgxman_linux_armv6.tar.gz"
      sha256 "db0209e3c1f038646cb5686dbd8d6e17ea66be722b18dc3c57d2730cbe996a19"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgxman/release/releases/download/v0.1.19/pgxman_linux_arm64.tar.gz"
      sha256 "4dc3363faeeb40abda096fcfe51a82fbb7d4eb9cde615cf428e6f9b729014d46"

      def install
        bin.install "bin/pgxman"
        man1.install Dir["docs/man/man1/pgxman*.1"]
        generate_completions_from_executable(bin/"pgxman", "completion")
      end
    end
  end

  head "https://github.com/pgxman/pgxman.git"

  test do
    assert_match(/pgxman version/, shell_output("#{bin}/pgxman --version"))
  end
end
