# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgxman < Formula
  desc "PostgreSQL Extensions Manager"
  homepage "https://github.com/pgxman/pgxman"
  version "0.0.24"
  license "Apache 2.0"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pgxman/release/releases/download/v0.0.24/pgxman_darwin_amd64.tar.gz"
      sha256 "1dd6ab6beec49c00848f738eed1034ebb90802d6a118880537f145eeefb7df2f"

      def install
        bin.install "bin/pgxman"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pgxman/release/releases/download/v0.0.24/pgxman_darwin_arm64.tar.gz"
      sha256 "5c7770a87e19cbfc050547357a99b4a3749b7612f09ec1b87ac6a4eed56bd045"

      def install
        bin.install "bin/pgxman"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pgxman/release/releases/download/v0.0.24/pgxman_linux_amd64.tar.gz"
      sha256 "0b9abf3600e3c4d8fa9509515444e4a3ad85bb5ca09a565e37cef786aed28ba0"

      def install
        bin.install "bin/pgxman"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/pgxman/release/releases/download/v0.0.24/pgxman_linux_armv6.tar.gz"
      sha256 "3350d94c75ec37a05c5d833e1d975f4fb35b78ba732feecd4eaf0b423a71334b"

      def install
        bin.install "bin/pgxman"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pgxman/release/releases/download/v0.0.24/pgxman_linux_arm64.tar.gz"
      sha256 "b1f418d1d7f03f910585feb87aa2378bce87cb8a440a7f256d3f4a1c08fcd6a7"

      def install
        bin.install "bin/pgxman"
      end
    end
  end

  head "https://github.com/pgxman/pgxman.git"

  test do
    assert_match(/pgxman version/, shell_output("#{bin}/pgxman --version"))
  end
end
